# fly.toml app configuration file generated for phantom-tv on 2026-04-14T00:26:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phantom-tv'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/phantom.db'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'phantom_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
