services:
  - type: web
    name: phantom-tv
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
