/* ═══════════════════════════════════════════════════════════════
   PHANTOM TV — Complete Channel Catalog (460+ chaînes)

   Streams réels utilisés pour les chaînes publiques connues.
   Pour les chaînes payantes/protégées : flux de démonstration HLS.
   L'admin peut remplacer les URLs via Import M3U ou le panel Admin.
   ═══════════════════════════════════════════════════════════════ */

// ── Flux publics réels connus ───────────────────────────────────
const R = {
  F24_FR:       'https://stream.france24.com/hls/live/2037801/F24_FR_HI_HLS/master.m3u8',
  F24_EN:       'https://stream.france24.com/hls/live/2037800/F24_EN_HI_HLS/master.m3u8',
  F24_AR:       'https://stream.france24.com/hls/live/2037803/F24_AR_HI_HLS/master.m3u8',
  F24_ES:       'https://stream.france24.com/hls/live/2037802/F24_ES_HI_HLS/master.m3u8',
  AJE:          'https://live-hls-web-aja.getaj.net/AJA/03.m3u8',
  AJA:          'https://live-hls-web-aja.getaj.net/AJA/01.m3u8',
  CGTN:         'https://news.cgtn.com/resource/live/chanel/cgtn.m3u8',
  CGTN_AR:      'https://news.cgtn.com/resource/live/chanel/cgtn-arabic.m3u8',
  CGTN_FR:      'https://news.cgtn.com/resource/live/chanel/cgtn-french.m3u8',
  CGTN_ES:      'https://news.cgtn.com/resource/live/chanel/cgtn-spanish.m3u8',
  CGTN_RU:      'https://news.cgtn.com/resource/live/chanel/cgtn-russian.m3u8',
  DW_EN:        'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',
  DW_DE:        'https://dwamdstream104.akamaized.net/hls/live/2015531/dwstream104/index.m3u8',
  DW_ES:        'https://dwamdstream106.akamaized.net/hls/live/2015533/dwstream106/index.m3u8',
  DW_AR:        'https://dwamdstream103.akamaized.net/hls/live/2015530/dwstream103/index.m3u8',
  DW_FR:        'https://dwamdstream107.akamaized.net/hls/live/2015534/dwstream107/index.m3u8',
  NASA1:        'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
  NASA2:        'https://ntv2.akamaized.net/hls/live/2014076/NASA-NTV2-HLS/master.m3u8',
  TRT_W:        'https://trtworld.live.trt.com.tr/hls/live/716038/trtworld/master.m3u8',
  TRT_H:        'https://trthaber.live.trt.com.tr/hls/live/571387/trthaber/master.m3u8',
  NHK:          'https://nhkworldjpnhkwlive-lh.akamaized.net/i/nhkworldjpnhkwlive@627588/master.m3u8',
  KBS:          'https://hlslive-worldcast.aws.kbs.co.kr/kbs_world/kbs_world.m3u8',
  ARIRANG:      'https://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8',
  EURONEWS_FR:  'https://euronews-euronews-livefr-ntprd.amagi.tv/playlist.m3u8',
  EURONEWS_EN:  'https://euronews-euronews-liveen-ntprd.amagi.tv/playlist.m3u8',
  EURONEWS_DE:  'https://euronews-euronews-livede-ntprd.amagi.tv/playlist.m3u8',
  EURONEWS_ES:  'https://euronews-euronews-livees-ntprd.amagi.tv/playlist.m3u8',
  EURONEWS_IT:  'https://euronews-euronews-liveit-ntprd.amagi.tv/playlist.m3u8',
  EURONEWS_PT:  'https://euronews-euronews-livept-ntprd.amagi.tv/playlist.m3u8',
  EURONEWS_RU:  'https://euronews-euronews-liveru-ntprd.amagi.tv/playlist.m3u8',
  BLOOMBERG:    'https://cdn3.wowza.com/1/ejBGVnFIOW9zNEFp/cB7Yz5/hls/live/playlist.m3u8',
  SKY_NEWS:     'https://skynews-vh.akamaized.net/i/skynews_universal@185350/master.m3u8',
};

// ── Flux de démonstration HLS (remplacez par vos vraies URLs) ──
const DEMO = 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8';

// ── Logos ───────────────────────────────────────────────────────
const L = {
  F24:       'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/France_24_logo_%282016%29.svg/120px-France_24_logo_%282016%29.svg.png',
  AJE:       'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Aljazeera_eng.svg/120px-Aljazeera_eng.svg.png',
  DW:        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_symbol_2012.svg/120px-Deutsche_Welle_symbol_2012.svg.png',
  CGTN:      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/CGTN-logo.svg/120px-CGTN-logo.svg.png',
  EURONEWS:  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Euronews_logo_%282022%29.svg/120px-Euronews_logo_%282022%29.svg.png',
  BLOOMBERG: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Bloomberg_Television_logo.svg/120px-Bloomberg_Television_logo.svg.png',
  SKY_NEWS:  'https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Sky_News_logo_2020.svg/120px-Sky_News_logo_2020.svg.png',
  NASA:      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/120px-NASA_logo.svg.png',
  TRT:       'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/TRT_World_Logo_%282017%29.svg/120px-TRT_World_Logo_%282017%29.svg.png',
  NHK:       'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/NHK_logo_2020.svg/120px-NHK_logo_2020.svg.png',
  KBS:       'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/KBS_World_TV_%282016%29.svg/120px-KBS_World_TV_%282016%29.svg.png',
  BBC:       'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/BBC_One_logo_2021.svg/120px-BBC_One_logo_2021.svg.png',
  CNN:       'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/120px-CNN.svg.png',
  BFM:       'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/BFMTV_Logo_2017.svg/120px-BFMTV_Logo_2017.svg.png',
  RT:        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Russia_Today_Logo.svg/120px-Russia_Today_Logo.svg.png',
  MTVE:      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/MTV_2021.svg/120px-MTV_2021.svg.png',
  DISCO:     'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Discovery_Channel_logo_2019.svg/120px-Discovery_Channel_logo_2019.svg.png',
  NATGEO:    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/24044-004-3466B9C4.jpg/120px-24044-004-3466B9C4.jpg',
  HISTORY:   'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/History_logo_2021.svg/120px-History_logo_2021.svg.png',
  DSNYCHN:   'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Disney_Channel_logo.svg/120px-Disney_Channel_logo.svg.png',
  CARTNW:    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/120px-Cartoon_Network_2010_logo.svg.png',
  NICKELOD:  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Nickelodeon_2023_logo.svg/120px-Nickelodeon_2023_logo.svg.png',
  BOOMERANG: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Boomerang_channel_logo.svg/120px-Boomerang_channel_logo.svg.png',
  ESPN:      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/120px-ESPN_wordmark.svg.png',
  EUROSPORT: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eurosport_logo_2015.svg/120px-Eurosport_logo_2015.svg.png',
  OLYMPIC:   'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_Channel_logo.svg/120px-Olympic_Channel_logo.svg.png',
  ARTE:      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Arte_logo.svg/120px-Arte_logo.svg.png',
  ANIMAL:    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Animal_Planet_Logo.svg/120px-Animal_Planet_Logo.svg.png',
  PBS:       'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/PBS_logo_%282019%29.svg/120px-PBS_logo_%282019%29.svg.png',
  VH1:       'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/VH1_Logo_2019.svg/120px-VH1_Logo_2019.svg.png',
  TRACE:     'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Trace_Urban_logo_2019.svg/120px-Trace_Urban_logo_2019.svg.png',
  TF1:       'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/TF1_2013_logo.svg/120px-TF1_2013_logo.svg.png',
  M6:        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Logo_de_M6.svg/120px-Logo_de_M6.svg.png',
  GULLI:     'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Logo_Gulli.svg/120px-Logo_Gulli.svg.png',
  TIJI:      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Tiji_logo_2019.svg/120px-Tiji_logo_2019.svg.png',
  BABYTV:    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/BabyTV_logo.svg/120px-BabyTV_logo.svg.png',
  ARIRANG:   'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Arirang_TV_logo.svg/120px-Arirang_TV_logo.svg.png',
};

// ── CATALOGUE COMPLET ───────────────────────────────────────────
// Format: { name, logo, url, cat, quality, country, group, featured }
// cat = slug de catégorie

const channels = [

  // ════════════════════════════════════════════
  //  📰 ACTUALITÉS & INFORMATION (60 chaînes)
  // ════════════════════════════════════════════

  // France 24
  { name:'France 24 Français',     logo:L.F24,       url:R.F24_FR,      cat:'news', quality:'HD',  country:'FR', group:'France 24', featured:true },
  { name:'France 24 English',      logo:L.F24,       url:R.F24_EN,      cat:'news', quality:'HD',  country:'FR', group:'France 24', featured:true },
  { name:'France 24 عربي',         logo:L.F24,       url:R.F24_AR,      cat:'news', quality:'HD',  country:'FR', group:'France 24' },
  { name:'France 24 Español',      logo:L.F24,       url:R.F24_ES,      cat:'news', quality:'HD',  country:'FR', group:'France 24' },

  // Al Jazeera
  { name:'Al Jazeera English',     logo:L.AJE,       url:R.AJE,         cat:'news', quality:'HD',  country:'QA', group:'Al Jazeera', featured:true },
  { name:'Al Jazeera Arabic',      logo:L.AJE,       url:R.AJA,         cat:'news', quality:'HD',  country:'QA', group:'Al Jazeera' },
  { name:'Al Jazeera Mubasher',    logo:L.AJE,       url:DEMO,          cat:'news', quality:'HD',  country:'QA', group:'Al Jazeera' },
  { name:'Al Jazeera Documentary', logo:L.AJE,       url:DEMO,          cat:'news', quality:'HD',  country:'QA', group:'Al Jazeera' },

  // Deutsche Welle
  { name:'DW English',             logo:L.DW,        url:R.DW_EN,       cat:'news', quality:'HD',  country:'DE', group:'Deutsche Welle', featured:true },
  { name:'DW Deutsch',             logo:L.DW,        url:R.DW_DE,       cat:'news', quality:'HD',  country:'DE', group:'Deutsche Welle' },
  { name:'DW Español',             logo:L.DW,        url:R.DW_ES,       cat:'news', quality:'HD',  country:'DE', group:'Deutsche Welle' },
  { name:'DW Arabic',              logo:L.DW,        url:R.DW_AR,       cat:'news', quality:'HD',  country:'DE', group:'Deutsche Welle' },
  { name:'DW Français',            logo:L.DW,        url:R.DW_FR,       cat:'news', quality:'HD',  country:'DE', group:'Deutsche Welle' },

  // CGTN
  { name:'CGTN',                   logo:L.CGTN,      url:R.CGTN,        cat:'news', quality:'FHD', country:'CN', group:'CGTN', featured:true },
  { name:'CGTN Français',          logo:L.CGTN,      url:R.CGTN_FR,     cat:'news', quality:'HD',  country:'CN', group:'CGTN' },
  { name:'CGTN Español',           logo:L.CGTN,      url:R.CGTN_ES,     cat:'news', quality:'HD',  country:'CN', group:'CGTN' },
  { name:'CGTN Arabic',            logo:L.CGTN,      url:R.CGTN_AR,     cat:'news', quality:'HD',  country:'CN', group:'CGTN' },
  { name:'CGTN Russian',           logo:L.CGTN,      url:R.CGTN_RU,     cat:'news', quality:'HD',  country:'CN', group:'CGTN' },

  // Euronews
  { name:'Euronews Français',      logo:L.EURONEWS,  url:R.EURONEWS_FR, cat:'news', quality:'HD',  country:'EU', group:'Euronews', featured:true },
  { name:'Euronews English',       logo:L.EURONEWS,  url:R.EURONEWS_EN, cat:'news', quality:'HD',  country:'EU', group:'Euronews' },
  { name:'Euronews Deutsch',       logo:L.EURONEWS,  url:R.EURONEWS_DE, cat:'news', quality:'HD',  country:'EU', group:'Euronews' },
  { name:'Euronews Español',       logo:L.EURONEWS,  url:R.EURONEWS_ES, cat:'news', quality:'HD',  country:'EU', group:'Euronews' },
  { name:'Euronews Italiano',      logo:L.EURONEWS,  url:R.EURONEWS_IT, cat:'news', quality:'HD',  country:'EU', group:'Euronews' },
  { name:'Euronews Português',     logo:L.EURONEWS,  url:R.EURONEWS_PT, cat:'news', quality:'HD',  country:'EU', group:'Euronews' },
  { name:'Euronews Русский',       logo:L.EURONEWS,  url:R.EURONEWS_RU, cat:'news', quality:'HD',  country:'EU', group:'Euronews' },

  // Bloomberg
  { name:'Bloomberg TV',           logo:L.BLOOMBERG, url:R.BLOOMBERG,   cat:'news', quality:'HD',  country:'US', group:'Bloomberg', featured:true },
  { name:'Bloomberg Markets',      logo:L.BLOOMBERG, url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'Bloomberg' },

  // Sky News
  { name:'Sky News',               logo:L.SKY_NEWS,  url:R.SKY_NEWS,    cat:'news', quality:'HD',  country:'GB', group:'Sky', featured:true },
  { name:'Sky News Arabia',        logo:L.SKY_NEWS,  url:DEMO,          cat:'news', quality:'HD',  country:'AE', group:'Sky' },
  { name:'Sky News Australia',     logo:L.SKY_NEWS,  url:DEMO,          cat:'news', quality:'HD',  country:'AU', group:'Sky' },

  // US News
  { name:'CNN International',      logo:L.CNN,       url:DEMO,          cat:'news', quality:'FHD', country:'US', group:'CNN' },
  { name:'CNN en Español',         logo:L.CNN,       url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'CNN' },
  { name:'CNN USA',                logo:L.CNN,       url:DEMO,          cat:'news', quality:'FHD', country:'US', group:'CNN' },
  { name:'MSNBC',                  logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'NBC' },
  { name:'Fox News',               logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'Fox' },
  { name:'ABC News Live',          logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'ABC' },
  { name:'NBC News NOW',           logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'NBC' },
  { name:'CBS News',               logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'CBS' },
  { name:'PBS NewsHour',           logo:L.PBS,       url:DEMO,          cat:'news', quality:'HD',  country:'US', group:'PBS' },

  // France
  { name:'BFM TV',                 logo:L.BFM,       url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'BFM', featured:true },
  { name:'BFM Business',           logo:L.BFM,       url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'BFM' },
  { name:'BFM Paris',              logo:L.BFM,       url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'BFM' },
  { name:'LCI',                    logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'TF1 Group' },
  { name:'CNews',                  logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'Canal+' },
  { name:'LCP Assemblée',          logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'LCP' },
  { name:'France Info TV',         logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'France TV' },
  { name:'Public Sénat',           logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'FR', group:'Sénat' },

  // International News
  { name:'TRT World',              logo:L.TRT,       url:R.TRT_W,       cat:'news', quality:'HD',  country:'TR', group:'TRT', featured:true },
  { name:'TRT Haber',              logo:L.TRT,       url:R.TRT_H,       cat:'news', quality:'HD',  country:'TR', group:'TRT' },
  { name:'NHK World Japan',        logo:L.NHK,       url:R.NHK,         cat:'news', quality:'HD',  country:'JP', group:'NHK' },
  { name:'KBS World',              logo:L.KBS,       url:R.KBS,         cat:'news', quality:'HD',  country:'KR', group:'KBS' },
  { name:'Arirang TV',             logo:L.ARIRANG,   url:R.ARIRANG,     cat:'news', quality:'HD',  country:'KR', group:'Arirang' },
  { name:'Russia Today Français',  logo:L.RT,        url:DEMO,          cat:'news', quality:'HD',  country:'RU', group:'RT' },
  { name:'Russia Today English',   logo:L.RT,        url:DEMO,          cat:'news', quality:'HD',  country:'RU', group:'RT' },
  { name:'Russia Today Arabic',    logo:L.RT,        url:DEMO,          cat:'news', quality:'HD',  country:'RU', group:'RT' },
  { name:'Press TV',               logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'IR', group:'IRIB' },
  { name:'WION News',              logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'IN', group:'WION' },
  { name:'Geo News',               logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'PK', group:'Geo' },
  { name:'ARY News',               logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'PK', group:'ARY' },
  { name:'Al Arabiya',             logo:null,        url:DEMO,          cat:'news', quality:'FHD', country:'AE', group:'MBC' },
  { name:'Al Mayadeen',            logo:null,        url:DEMO,          cat:'news', quality:'HD',  country:'LB', group:'Mayadeen' },
  { name:'NASA TV',                logo:L.NASA,      url:R.NASA1,       cat:'news', quality:'HD',  country:'US', group:'NASA', featured:true },
  { name:'NASA TV Media',          logo:L.NASA,      url:R.NASA2,       cat:'news', quality:'HD',  country:'US', group:'NASA' },

  // ════════════════════════════════════════════
  //  ⚽ SPORTS (55 chaînes)
  // ════════════════════════════════════════════

  { name:"L'Équipe TV",            logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'FR', group:'Équipe', featured:true },
  { name:'Eurosport 1',            logo:L.EUROSPORT, url:DEMO, cat:'sports', quality:'FHD', country:'EU', group:'Eurosport', featured:true },
  { name:'Eurosport 2',            logo:L.EUROSPORT, url:DEMO, cat:'sports', quality:'FHD', country:'EU', group:'Eurosport' },
  { name:'Canal+ Sport 1',         logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'FR', group:'Canal+' },
  { name:'Canal+ Sport 2',         logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'FR', group:'Canal+' },
  { name:'Canal+ Sport 3',         logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'FR', group:'Canal+' },
  { name:'RMC Sport 1',            logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'FR', group:'RMC' },
  { name:'RMC Sport 2',            logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'FR', group:'RMC' },
  { name:'beIN Sports 1',          logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'QA', group:'beIN', featured:true },
  { name:'beIN Sports 2',          logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'QA', group:'beIN' },
  { name:'beIN Sports 3',          logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'QA', group:'beIN' },
  { name:'beIN Sports Max 1',      logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'QA', group:'beIN' },
  { name:'beIN Sports Max 2',      logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'QA', group:'beIN' },
  { name:'ESPN',                   logo:L.ESPN,      url:DEMO, cat:'sports', quality:'FHD', country:'US', group:'ESPN', featured:true },
  { name:'ESPN 2',                 logo:L.ESPN,      url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'ESPN' },
  { name:'ESPN 3',                 logo:L.ESPN,      url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'ESPN' },
  { name:'ESPN Classic',           logo:L.ESPN,      url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'ESPN' },
  { name:'Sky Sports Main Event',  logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'GB', group:'Sky Sports' },
  { name:'Sky Sports Football',    logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'GB', group:'Sky Sports' },
  { name:'Sky Sports Premier Lg',  logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'GB', group:'Sky Sports' },
  { name:'Sky Sports F1',          logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'Sky Sports' },
  { name:'Sky Sports Cricket',     logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'Sky Sports' },
  { name:'Sky Sports News',        logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'Sky Sports' },
  { name:'BT Sport 1',             logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'GB', group:'BT Sport' },
  { name:'BT Sport 2',             logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'GB', group:'BT Sport' },
  { name:'BT Sport 3',             logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'BT Sport' },
  { name:'TNT Sports 1',           logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'GB', group:'TNT Sports' },
  { name:'TNT Sports 2',           logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'TNT Sports' },
  { name:'Olympic Channel',        logo:L.OLYMPIC,   url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'Olympic' },
  { name:'NFL Network',            logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'NFL' },
  { name:'NBA TV',                 logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'NBA' },
  { name:'MLB Network',            logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'MLB' },
  { name:'NHL Network',            logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'NHL' },
  { name:'Tennis Channel',         logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'Tennis' },
  { name:'Golf Channel',           logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'Golf' },
  { name:'MotorTrend TV',          logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'Motor' },
  { name:'Fight Network',          logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'CA', group:'Fight' },
  { name:'Eleven Sports 1',        logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'PL', group:'Eleven' },
  { name:'Eleven Sports 2',        logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'PL', group:'Eleven' },
  { name:'LaLiga TV',              logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'ES', group:'LaLiga' },
  { name:'SuperSport 1',           logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'ZA', group:'SuperSport' },
  { name:'SuperSport 2',           logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'ZA', group:'SuperSport' },
  { name:'Redbull TV',             logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'AT', group:'RedBull' },
  { name:'Racing TV',              logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'Racing' },
  { name:'Star Sports 1',          logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'IN', group:'Star Sports' },
  { name:'Star Sports 2',          logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'IN', group:'Star Sports' },
  { name:'Sony LIV Sports',        logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'IN', group:'Sony' },
  { name:'Discovery Sports',       logo:L.DISCO,     url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'Discovery' },
  { name:'DAZN 1',                 logo:null,        url:DEMO, cat:'sports', quality:'4K',  country:'DE', group:'DAZN', featured:true },
  { name:'DAZN 2',                 logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'DE', group:'DAZN' },
  { name:'Bundesliga TV',          logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'DE', group:'DFL' },
  { name:'Serie A Pass',           logo:null,        url:DEMO, cat:'sports', quality:'FHD', country:'IT', group:'Lega Serie A' },
  { name:'Fishing TV',             logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'Fishing' },
  { name:'Horse Racing TV',        logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'GB', group:'Racing' },
  { name:'PowerSports TV',         logo:null,        url:DEMO, cat:'sports', quality:'HD',  country:'US', group:'Power' },

  // ════════════════════════════════════════════
  //  🎬 FILMS (65 chaînes)
  // ════════════════════════════════════════════

  { name:'Canal+ Cinéma',          logo:null, url:DEMO, cat:'movies', quality:'4K',  country:'FR', group:'Canal+', featured:true },
  { name:'Canal+ Cinéma 2',        logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'FR', group:'Canal+' },
  { name:'OCS Géants',             logo:null, url:DEMO, cat:'movies', quality:'4K',  country:'FR', group:'OCS', featured:true },
  { name:'OCS Choc',               logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'FR', group:'OCS' },
  { name:'OCS Novo',               logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'FR', group:'OCS' },
  { name:'OCS Max',                logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'FR', group:'OCS' },
  { name:'Ciné+ Classic',          logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Ciné+' },
  { name:'Ciné+ Premier',          logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'FR', group:'Ciné+' },
  { name:'Ciné+ Club',             logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Ciné+' },
  { name:'Ciné+ Frisson',          logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Ciné+' },
  { name:'Ciné+ Famiz',            logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Ciné+' },
  { name:'TCM Classic Movies',     logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'TCM', featured:true },
  { name:'TCM 2',                  logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'TCM' },
  { name:'Paramount Channel',      logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Paramount' },
  { name:'Paramount Channel 2',    logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Paramount' },
  { name:'AMC',                    logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'AMC' },
  { name:'IFC',                    logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'IFC' },
  { name:'Sundance TV',            logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Sundance' },
  { name:'FX',                     logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'FX' },
  { name:'FXX',                    logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'FX' },
  { name:'FX Movie Channel',       logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'FX' },
  { name:'Starz',                  logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Starz' },
  { name:'Starz Cinema',           logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Starz' },
  { name:'Starz In Black',         logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Starz' },
  { name:'Epix',                   logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Epix' },
  { name:'Epix 2',                 logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Epix' },
  { name:'Epix Hits',              logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Epix' },
  { name:'MGM HD',                 logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'MGM' },
  { name:'Sony Movies',            logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Sony' },
  { name:'Sony Movies Classic',    logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Sony' },
  { name:'Sony Movies Action',     logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Sony' },
  { name:'Universal TV',           logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Universal' },
  { name:'HBO',                    logo:null, url:DEMO, cat:'movies', quality:'4K',  country:'US', group:'HBO', featured:true },
  { name:'HBO 2',                  logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'HBO' },
  { name:'HBO Comedy',             logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'HBO' },
  { name:'HBO Family',             logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'HBO' },
  { name:'HBO Latino',             logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'HBO' },
  { name:'Showtime',               logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Showtime' },
  { name:'Showtime Extreme',       logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Showtime' },
  { name:'Showtime Women',         logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Showtime' },
  { name:'Cinemax',                logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'Cinemax' },
  { name:'MoreMax',                logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Cinemax' },
  { name:'ActionMax',              logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Cinemax' },
  { name:'Encore',                 logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Encore' },
  { name:'Encore Westerns',        logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Encore' },
  { name:'Encore Black',           logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'Encore' },
  { name:'FilmBox HD',             logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'PL', group:'FilmBox' },
  { name:'FilmBox Plus',           logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'PL', group:'FilmBox' },
  { name:'FilmBox Stars',          logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'PL', group:'FilmBox' },
  { name:'FilmBox Arthouse',       logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'PL', group:'FilmBox' },
  { name:'Eurochannel',            logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'EU', group:'Euro' },
  { name:'Rakuten TV',             logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'JP', group:'Rakuten' },
  { name:'MUBI',                   logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'US', group:'MUBI' },
  { name:'Bollywood TV',           logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'IN', group:'Bollywood' },
  { name:'Zee Cinema',             logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'IN', group:'Zee' },
  { name:'Star Gold',              logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'IN', group:'Star' },
  { name:'BET Movies',             logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'BET' },
  { name:'AllBlk',                 logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'AllBlk' },
  { name:'Rotana Cinema',          logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'SA', group:'Rotana' },
  { name:'TBN Films',              logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'US', group:'TBN' },
  { name:'Kino Polska',            logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'PL', group:'Kino' },
  { name:'Meuzz Cinema',           logo:null, url:DEMO, cat:'movies', quality:'FHD', country:'FR', group:'Meuzz' },
  { name:'Action Extrême',         logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Action' },
  { name:'Polar+',                 logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Polar' },
  { name:'Comédie+',               logo:null, url:DEMO, cat:'movies', quality:'HD',  country:'FR', group:'Comédie' },

  // ════════════════════════════════════════════
  //  📺 SÉRIES (50 chaînes)
  // ════════════════════════════════════════════

  { name:'AMC Series',             logo:null, url:DEMO, cat:'series', quality:'FHD', country:'US', group:'AMC', featured:true },
  { name:'The CW',                 logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'CW' },
  { name:'USA Network',            logo:null, url:DEMO, cat:'series', quality:'FHD', country:'US', group:'USA' },
  { name:'TNT',                    logo:null, url:DEMO, cat:'series', quality:'FHD', country:'US', group:'TNT' },
  { name:'TBS',                    logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'TBS' },
  { name:'Bravo',                  logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Bravo' },
  { name:'E! Entertainment',       logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'E!' },
  { name:'Oxygen',                 logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Oxygen' },
  { name:'Lifetime',               logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Lifetime' },
  { name:'Lifetime Movie Network', logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Lifetime' },
  { name:'Hallmark Channel',       logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Hallmark' },
  { name:'Hallmark Movies & M.',   logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Hallmark' },
  { name:'WE tv',                  logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'WE tv' },
  { name:'OWN Network',            logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'OWN' },
  { name:'Freeform',               logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Freeform' },
  { name:'Syfy',                   logo:null, url:DEMO, cat:'series', quality:'FHD', country:'US', group:'Syfy' },
  { name:'A&E',                    logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'A&E' },
  { name:'TV Land',                logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'TV Land' },
  { name:'Viceland',               logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Vice' },
  { name:'Adult Swim',             logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'AS' },
  { name:'BET+',                   logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'BET' },
  { name:'Comedy Central',         logo:null, url:DEMO, cat:'series', quality:'FHD', country:'US', group:'Comedy' },
  { name:'BBC America',            logo:L.BBC, url:DEMO, cat:'series', quality:'FHD', country:'GB', group:'BBC' },
  { name:'BBC Three',              logo:L.BBC, url:DEMO, cat:'series', quality:'FHD', country:'GB', group:'BBC' },
  { name:'ITV2',                   logo:null, url:DEMO, cat:'series', quality:'HD',  country:'GB', group:'ITV' },
  { name:'ITV3',                   logo:null, url:DEMO, cat:'series', quality:'HD',  country:'GB', group:'ITV' },
  { name:'Channel 4 Series',       logo:null, url:DEMO, cat:'series', quality:'FHD', country:'GB', group:'C4' },
  { name:'E4',                     logo:null, url:DEMO, cat:'series', quality:'HD',  country:'GB', group:'C4' },
  { name:'Walter Presents',        logo:null, url:DEMO, cat:'series', quality:'FHD', country:'GB', group:'Walter' },
  { name:'MHz Choice',             logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'MHz' },
  { name:'TF1 Séries Films',       logo:L.TF1, url:DEMO, cat:'series', quality:'HD', country:'FR', group:'TF1' },
  { name:'Altice Studio',          logo:null, url:DEMO, cat:'series', quality:'HD',  country:'FR', group:'Altice' },
  { name:'Canal+ Series',          logo:null, url:DEMO, cat:'series', quality:'4K',  country:'FR', group:'Canal+', featured:true },
  { name:'OCS City',               logo:null, url:DEMO, cat:'series', quality:'FHD', country:'FR', group:'OCS' },
  { name:'Shudder',                logo:null, url:DEMO, cat:'series', quality:'FHD', country:'US', group:'Shudder' },
  { name:'Sundance Now',           logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'Sundance' },
  { name:'Arrow',                  logo:null, url:DEMO, cat:'series', quality:'HD',  country:'UK', group:'Arrow' },
  { name:'WGN America',            logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'WGN' },
  { name:'ION Television',         logo:null, url:DEMO, cat:'series', quality:'HD',  country:'US', group:'ION' },
  { name:'MBC Drama',              logo:null, url:DEMO, cat:'series', quality:'FHD', country:'AE', group:'MBC' },
  { name:'MBC 2',                  logo:null, url:DEMO, cat:'series', quality:'FHD', country:'AE', group:'MBC' },
  { name:'MBC Action',             logo:null, url:DEMO, cat:'series', quality:'FHD', country:'AE', group:'MBC' },
  { name:'StarWorld',              logo:null, url:DEMO, cat:'series', quality:'HD',  country:'IN', group:'Star' },
  { name:'Star Plus',              logo:null, url:DEMO, cat:'series', quality:'FHD', country:'IN', group:'Star' },
  { name:'Zee TV',                 logo:null, url:DEMO, cat:'series', quality:'FHD', country:'IN', group:'Zee' },
  { name:'Colors TV',              logo:null, url:DEMO, cat:'series', quality:'FHD', country:'IN', group:'Colors' },
  { name:'Sony Entertainment',     logo:null, url:DEMO, cat:'series', quality:'FHD', country:'IN', group:'Sony' },
  { name:'LBC Series',             logo:null, url:DEMO, cat:'series', quality:'HD',  country:'LB', group:'LBC' },
  { name:'Rotana Series',          logo:null, url:DEMO, cat:'series', quality:'HD',  country:'SA', group:'Rotana' },
  { name:'Netflix Originals',      logo:null, url:DEMO, cat:'series', quality:'4K',  country:'US', group:'Netflix', featured:true },

  // ════════════════════════════════════════════
  //  🎥 DOCUMENTAIRES (45 chaînes)
  // ════════════════════════════════════════════

  { name:'Discovery Channel',      logo:L.DISCO,  url:DEMO, cat:'docs', quality:'FHD', country:'US', group:'Discovery', featured:true },
  { name:'Discovery Science',      logo:L.DISCO,  url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Discovery Turbo',        logo:L.DISCO,  url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Discovery History',      logo:L.DISCO,  url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Discovery+ HD',          logo:L.DISCO,  url:DEMO, cat:'docs', quality:'FHD', country:'US', group:'Discovery' },
  { name:'National Geographic',    logo:L.NATGEO, url:DEMO, cat:'docs', quality:'4K',  country:'US', group:'NatGeo', featured:true },
  { name:'National Geographic Wild',logo:L.NATGEO,url:DEMO, cat:'docs', quality:'FHD', country:'US', group:'NatGeo' },
  { name:'NatGeo Mundo',           logo:L.NATGEO, url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'NatGeo' },
  { name:'NatGeo People',          logo:L.NATGEO, url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'NatGeo' },
  { name:'History Channel',        logo:L.HISTORY,url:DEMO, cat:'docs', quality:'FHD', country:'US', group:'History', featured:true },
  { name:'History 2 (H2)',         logo:L.HISTORY,url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'History' },
  { name:'History Hit',            logo:L.HISTORY,url:DEMO, cat:'docs', quality:'HD',  country:'GB', group:'History' },
  { name:'Smithsonian Channel',    logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Smithsonian' },
  { name:'Animal Planet',          logo:L.ANIMAL, url:DEMO, cat:'docs', quality:'FHD', country:'US', group:'Discovery' },
  { name:'BBC Earth',              logo:L.BBC,    url:DEMO, cat:'docs', quality:'4K',  country:'GB', group:'BBC', featured:true },
  { name:'BBC World Service',      logo:L.BBC,    url:DEMO, cat:'docs', quality:'HD',  country:'GB', group:'BBC' },
  { name:'Science Channel',        logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Investigation Discovery',logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Crime+Investigation',    logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'A&E' },
  { name:'True Crime Network',     logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Crime' },
  { name:'Oxygen True Crime',      logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Oxygen' },
  { name:'Reelz Channel',          logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Reelz' },
  { name:'Arte',                   logo:L.ARTE,   url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Arte', featured:true },
  { name:'Arte Concert',           logo:L.ARTE,   url:DEMO, cat:'docs', quality:'FHD', country:'FR', group:'Arte' },
  { name:'Planète+ A&E',           logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Planète+' },
  { name:'Planète+ Crime',         logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Planète+' },
  { name:'Planète+ No Limit',      logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Planète+' },
  { name:'Toute l\'Histoire',      logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Toute l\'Histoire' },
  { name:'Ushuaïa TV',             logo:null,     url:DEMO, cat:'docs', quality:'FHD', country:'FR', group:'Ushuaïa' },
  { name:'RMC Découverte',         logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'RMC' },
  { name:'Seasons',                logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Seasons' },
  { name:'Voyage',                 logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Voyage' },
  { name:'Escales',                logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'FR', group:'Escales' },
  { name:'PBS',                    logo:L.PBS,    url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'PBS' },
  { name:'CuriosityStream',        logo:null,     url:DEMO, cat:'docs', quality:'4K',  country:'US', group:'Curiosity' },
  { name:'Magellan TV',            logo:null,     url:DEMO, cat:'docs', quality:'FHD', country:'DE', group:'Magellan' },
  { name:'Real Crime',             logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'GB', group:'Real Crime' },
  { name:'TLC',                    logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Discovery Family',       logo:L.DISCO,  url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Magnolia Network',       logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Magnolia' },
  { name:'HGTV',                   logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Food Network',           logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Travel Channel',         logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'US', group:'Discovery' },
  { name:'Canal D',                logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'CA', group:'Bell' },
  { name:'DocuBox',                logo:null,     url:DEMO, cat:'docs', quality:'HD',  country:'PL', group:'DocuBox' },

  // ════════════════════════════════════════════
  //  🎵 MUSIQUE (35 chaînes)
  // ════════════════════════════════════════════

  { name:'MTV',                    logo:L.MTVE, url:DEMO, cat:'music', quality:'FHD', country:'US', group:'MTV', featured:true },
  { name:'MTV Hits',               logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV Dance',              logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV Base',               logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV Classic',            logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV Rocks',              logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV 00s',                logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV 80s',                logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'MTV 90s',                logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'VH1',                    logo:L.VH1,  url:DEMO, cat:'music', quality:'HD',  country:'US', group:'VH1', featured:true },
  { name:'VH1 Classic',            logo:L.VH1,  url:DEMO, cat:'music', quality:'HD',  country:'US', group:'VH1' },
  { name:'VH1 Soul',               logo:L.VH1,  url:DEMO, cat:'music', quality:'HD',  country:'US', group:'VH1' },
  { name:'BET Jams',               logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'US', group:'BET' },
  { name:'BET Hip Hop',            logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'US', group:'BET' },
  { name:'CMT',                    logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'US', group:'CMT' },
  { name:'CMT Music',              logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'US', group:'CMT' },
  { name:'MCM',                    logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'MCM', featured:true },
  { name:'MCM Top',                logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'MCM' },
  { name:'MCM Pop',                logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'MCM' },
  { name:'MCM Rock',               logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'MCM' },
  { name:'M6 Music',               logo:L.M6,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'M6' },
  { name:'M6 Music Black',         logo:L.M6,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'M6' },
  { name:'M6 Music Rock',          logo:L.M6,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'M6' },
  { name:'NRJ Hits',               logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'NRJ' },
  { name:'Trace Urban',            logo:L.TRACE,url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'Trace', featured:true },
  { name:'Trace Latina',           logo:L.TRACE,url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'Trace' },
  { name:'Trace Africa',           logo:L.TRACE,url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'Trace' },
  { name:'Trace Gospel',           logo:L.TRACE,url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'Trace' },
  { name:'Club MTV',               logo:L.MTVE, url:DEMO, cat:'music', quality:'HD',  country:'US', group:'MTV' },
  { name:'Dance Nation TV',        logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'EU', group:'Dance' },
  { name:'Mezzo Live HD',          logo:null,   url:DEMO, cat:'music', quality:'FHD', country:'FR', group:'Mezzo' },
  { name:'Jazz TV',                logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'US', group:'Jazz' },
  { name:'Luxe.TV',                logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'Luxe' },
  { name:'FIP TV',                 logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'FR', group:'Radio France' },
  { name:'Stingray Djazz',         logo:null,   url:DEMO, cat:'music', quality:'HD',  country:'CA', group:'Stingray' },

  // ════════════════════════════════════════════
  //  🧸 ENFANTS & JEUNESSE (42 chaînes)
  // ════════════════════════════════════════════

  { name:'Baby TV',                logo:L.BABYTV,   url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'Baby TV', featured:true },
  { name:'Baby First TV',          logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Baby First' },
  { name:'Nick Jr.',               logo:L.NICKELOD, url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Nickelodeon' },
  { name:'Nickelodeon',            logo:L.NICKELOD, url:DEMO, cat:'kids', quality:'FHD', country:'US', group:'Nickelodeon', featured:true },
  { name:'Nickelodeon UK',         logo:L.NICKELOD, url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'Nickelodeon' },
  { name:'TeenNick',               logo:L.NICKELOD, url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Nickelodeon' },
  { name:'NickToons',              logo:L.NICKELOD, url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Nickelodeon' },
  { name:'Cartoon Network',        logo:L.CARTNW,   url:DEMO, cat:'kids', quality:'FHD', country:'US', group:'CN', featured:true },
  { name:'Cartoon Network Too',    logo:L.CARTNW,   url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'CN' },
  { name:'Boomerang',              logo:L.BOOMERANG,url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'CN' },
  { name:'Disney Channel',         logo:L.DSNYCHN,  url:DEMO, cat:'kids', quality:'FHD', country:'US', group:'Disney', featured:true },
  { name:'Disney Junior',          logo:L.DSNYCHN,  url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Disney' },
  { name:'Disney XD',              logo:L.DSNYCHN,  url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Disney' },
  { name:'Disney Cinemagic',       logo:L.DSNYCHN,  url:DEMO, cat:'kids', quality:'HD',  country:'EU', group:'Disney' },
  { name:'CBeebies',               logo:L.BBC,      url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'BBC' },
  { name:'CBBC',                   logo:L.BBC,      url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'BBC' },
  { name:'Tiny Pop',               logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'Pop' },
  { name:'POP',                    logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'Pop' },
  { name:'Milkshake (Channel 5)',  logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'C5' },
  { name:'Tiji',                   logo:L.TIJI,     url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Tiji', featured:true },
  { name:'Gulli',                  logo:L.GULLI,    url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Gulli' },
  { name:'TF1 Kids',               logo:L.TF1,      url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'TF1' },
  { name:'Piwi+',                  logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Canal+' },
  { name:'Canal+ Kids',            logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Canal+' },
  { name:'Canal J',                logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Canal J' },
  { name:'Teletoon+',              logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Teletoon' },
  { name:'Boing',                  logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'IT', group:'Boing' },
  { name:'Super RTL',              logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'DE', group:'RTL' },
  { name:'KiKA',                   logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'DE', group:'KiKA' },
  { name:'Sprout',                 logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'NBC' },
  { name:'Noggin',                 logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Nick' },
  { name:'Universal Kids',         logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'NBC' },
  { name:'Hop!',                   logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'IL', group:'Hop' },
  { name:'Frisbee',                logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'IT', group:'Frisbee' },
  { name:'Jim Jam',                logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'GB', group:'Jim Jam' },
  { name:'Qubo',                   logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Qubo' },
  { name:'Kidz Bop TV',            logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'Kidz Bop' },
  { name:'OK3',                    logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'OK3' },
  { name:'Tele Junior',            logo:null,       url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Tele Junior' },
  { name:'Nat Geo Kids',           logo:L.NATGEO,   url:DEMO, cat:'kids', quality:'HD',  country:'US', group:'NatGeo' },
  { name:'Disney Junior FR',       logo:L.DSNYCHN,  url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'Disney' },
  { name:'Cartoon Network FR',     logo:L.CARTNW,   url:DEMO, cat:'kids', quality:'HD',  country:'FR', group:'CN' },

  // ════════════════════════════════════════════
  //  🌐 GÉNÉRALISTE & VARIÉTÉS (38 chaînes)
  // ════════════════════════════════════════════

  { name:'TF1',                    logo:L.TF1,  url:DEMO, cat:'international', quality:'FHD', country:'FR', group:'TF1 Group', featured:true },
  { name:'France 2',               logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'FR', group:'France TV' },
  { name:'France 3',               logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'FR', group:'France TV' },
  { name:'France 4',               logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'France TV' },
  { name:'France 5',               logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'France TV' },
  { name:'M6',                     logo:L.M6,   url:DEMO, cat:'international', quality:'FHD', country:'FR', group:'M6 Group' },
  { name:'W9',                     logo:L.M6,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'M6 Group' },
  { name:'TMC',                    logo:L.TF1,  url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'TF1 Group' },
  { name:'TFX',                    logo:L.TF1,  url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'TF1 Group' },
  { name:'C8',                     logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'Canal+' },
  { name:'CStar',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'Canal+' },
  { name:'6ter',                   logo:L.M6,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'M6 Group' },
  { name:'Chérie 25',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'NRJ Group' },
  { name:'Canal+',                 logo:null,   url:DEMO, cat:'international', quality:'4K',  country:'FR', group:'Canal+', featured:true },
  { name:'RMC Story',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'RMC' },
  { name:'RTL9',                   logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'LU', group:'RTL' },
  { name:'NRJ 12',                 logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'NRJ Group' },
  { name:'Paramount Network',      logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'US', group:'Paramount' },
  { name:'TLC France',             logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'Discovery' },
  { name:'Ovation',                logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'US', group:'Ovation' },
  { name:'Ion Television',         logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'US', group:'ION' },
  { name:'Circle TV',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'US', group:'Circle' },
  { name:'BBC One',                logo:L.BBC,  url:DEMO, cat:'international', quality:'FHD', country:'GB', group:'BBC', featured:true },
  { name:'BBC Two',                logo:L.BBC,  url:DEMO, cat:'international', quality:'HD',  country:'GB', group:'BBC' },
  { name:'BBC Four',               logo:L.BBC,  url:DEMO, cat:'international', quality:'HD',  country:'GB', group:'BBC' },
  { name:'ITV',                    logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'GB', group:'ITV' },
  { name:'Channel 4',              logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'GB', group:'C4' },
  { name:'Channel 5',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'GB', group:'C5' },
  { name:'ARD Das Erste',          logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'DE', group:'ARD' },
  { name:'ZDF',                    logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'DE', group:'ZDF' },
  { name:'ZDF Neo',                logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'DE', group:'ZDF' },
  { name:'ZDFinfo',                logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'DE', group:'ZDF' },
  { name:'Sat.1',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'DE', group:'ProSieben' },
  { name:'ProSieben',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'DE', group:'ProSieben' },
  { name:'RTL Deutschland',        logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'DE', group:'RTL DE' },
  { name:'Vox',                    logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'DE', group:'RTL DE' },
  { name:'RAI 1',                  logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'IT', group:'RAI' },
  { name:'RAI 2',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'IT', group:'RAI' },
  { name:'RAI 3',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'IT', group:'RAI' },
  { name:'RAI 4',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'IT', group:'RAI' },
  { name:'Canale 5',               logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'IT', group:'Mediaset' },
  { name:'Rete 4',                 logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'IT', group:'Mediaset' },
  { name:'Italia 1',               logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'IT', group:'Mediaset' },
  { name:'TVE La 1',               logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'ES', group:'RTVE' },
  { name:'TVE La 2',               logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'ES', group:'RTVE' },
  { name:'Antena 3',               logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'ES', group:'Atresmedia' },
  { name:'Cuatro',                 logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'ES', group:'Mediaset ES' },
  { name:'SIC',                    logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'PT', group:'SIC' },
  { name:'RTP1',                   logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'PT', group:'RTP' },
  { name:'RTP Internacional',      logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'PT', group:'RTP' },
  { name:'TVR 1',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'RO', group:'TVR' },
  { name:'TV Azteca',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'MX', group:'Azteca' },
  { name:'Televisa Canal de las E.',logo:null,  url:DEMO, cat:'international', quality:'HD',  country:'MX', group:'Televisa' },
  { name:'Univision',              logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'US', group:'Univision' },
  { name:'Telemundo',              logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'US', group:'Telemundo' },
  { name:'Multimedios',            logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'MX', group:'Multimedios' },
  { name:'Mega (Chile)',           logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'CL', group:'Mega' },
  { name:'Canal 13 Chile',         logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'CL', group:'C13' },
  { name:'TVN Chile',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'CL', group:'TVN' },
  { name:'Globo',                  logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'BR', group:'Globo' },
  { name:'Record TV Brasil',       logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BR', group:'Record' },
  { name:'SBT Brasil',             logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BR', group:'SBT' },
  { name:'MBC',                    logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'AE', group:'MBC' },
  { name:'LBC Lebanon',            logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'LB', group:'LBC' },
  { name:'Dubai TV',               logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'AE', group:'Dubai Media' },
  { name:'Abu Dhabi TV',           logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'AE', group:'ADMC' },
  { name:'TV5 Monde',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'FR', group:'TV5' },
  { name:'TVI Portugal',           logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'PT', group:'TVI' },
  { name:'Rai News 24',            logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'IT', group:'RAI' },
  { name:'HRT 1',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'HR', group:'HRT' },
  { name:'NOVA (CZ)',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'CZ', group:'CME' },
  { name:'TVP 1',                  logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'PL', group:'TVP' },
  { name:'Polsat',                 logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'PL', group:'Polsat' },
  { name:'NTV Russia',             logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'RU', group:'NTV' },
  { name:'Channel One Russia',     logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'RU', group:'Channel 1' },
  { name:'TRT 1',                  logo:L.TRT,  url:DEMO, cat:'international', quality:'FHD', country:'TR', group:'TRT' },

  // ════════════════════════════════════════════
  //  🕌 RELIGION & SPIRITUALITÉ (18 chaînes)
  // ════════════════════════════════════════════

  { name:'KTO TV',                 logo:null, url:DEMO, cat:'international', quality:'HD', country:'FR', group:'KTO', featured:false },
  { name:'Huda TV',                logo:null, url:DEMO, cat:'international', quality:'HD', country:'AE', group:'Huda' },
  { name:'Peace TV',               logo:null, url:DEMO, cat:'international', quality:'HD', country:'GB', group:'Peace TV' },
  { name:'Islam Channel',          logo:null, url:DEMO, cat:'international', quality:'HD', country:'GB', group:'Islam' },
  { name:'TBN (Trinity Broadcasting)',logo:null,url:DEMO,cat:'international',quality:'HD', country:'US', group:'TBN' },
  { name:'Daystar',                logo:null, url:DEMO, cat:'international', quality:'HD', country:'US', group:'Daystar' },
  { name:'EWTN',                   logo:null, url:DEMO, cat:'international', quality:'HD', country:'US', group:'EWTN' },
  { name:'GOD TV',                 logo:null, url:DEMO, cat:'international', quality:'HD', country:'GB', group:'GOD TV' },
  { name:'Vision TV',              logo:null, url:DEMO, cat:'international', quality:'HD', country:'CA', group:'Vision' },
  { name:'Al Quran Al Kareem',     logo:null, url:DEMO, cat:'international', quality:'HD', country:'SA', group:'Al Quran' },
  { name:'Iqraa TV',               logo:null, url:DEMO, cat:'international', quality:'HD', country:'SA', group:'Iqraa' },
  { name:'Nour TV',                logo:null, url:DEMO, cat:'international', quality:'HD', country:'AE', group:'Nour' },
  { name:'Risala TV',              logo:null, url:DEMO, cat:'international', quality:'HD', country:'SA', group:'Risala' },
  { name:'Hidaya TV',              logo:null, url:DEMO, cat:'international', quality:'HD', country:'US', group:'Hidaya' },
  { name:'Safwa TV',               logo:null, url:DEMO, cat:'international', quality:'HD', country:'EG', group:'Safwa' },
  { name:'CBN (Christian Bdcst N)',logo:null, url:DEMO, cat:'international', quality:'HD', country:'US', group:'CBN' },
  { name:'Salt + Light',           logo:null, url:DEMO, cat:'international', quality:'HD', country:'CA', group:'S+L' },
  { name:'Mezzo Classique',        logo:null, url:DEMO, cat:'music',         quality:'HD', country:'FR', group:'Mezzo' },

  // ════════════════════════════════════════════
  //  🔞 ADULTES (17 chaînes)
  // ════════════════════════════════════════════

  { name:'Canal+ Adult',           logo:null, url:DEMO, cat:'adults', quality:'HD', country:'FR', group:'Canal+' },
  { name:'XXL',                    logo:null, url:DEMO, cat:'adults', quality:'HD', country:'FR', group:'XXL' },
  { name:'Penthouse TV',           logo:null, url:DEMO, cat:'adults', quality:'HD', country:'US', group:'Penthouse' },
  { name:'Playboy TV',             logo:null, url:DEMO, cat:'adults', quality:'HD', country:'US', group:'Playboy' },
  { name:'Hustler TV',             logo:null, url:DEMO, cat:'adults', quality:'HD', country:'US', group:'Hustler' },
  { name:'Dusk Channel',           logo:null, url:DEMO, cat:'adults', quality:'HD', country:'GB', group:'Dusk' },
  { name:'Dorcel TV',              logo:null, url:DEMO, cat:'adults', quality:'FHD',country:'FR', group:'Dorcel' },
  { name:'Dorcel XXX',             logo:null, url:DEMO, cat:'adults', quality:'FHD',country:'FR', group:'Dorcel' },
  { name:'Private TV',             logo:null, url:DEMO, cat:'adults', quality:'HD', country:'ES', group:'Private' },
  { name:'Brazzers TV',            logo:null, url:DEMO, cat:'adults', quality:'FHD',country:'CA', group:'Brazzers' },
  { name:'Reality Kings TV',       logo:null, url:DEMO, cat:'adults', quality:'HD', country:'US', group:'RK' },
  { name:'Vivid TV',               logo:null, url:DEMO, cat:'adults', quality:'HD', country:'US', group:'Vivid' },
  { name:'Red Light 1',            logo:null, url:DEMO, cat:'adults', quality:'HD', country:'NL', group:'Red Light' },
  { name:'Red Light 2',            logo:null, url:DEMO, cat:'adults', quality:'HD', country:'NL', group:'Red Light' },
  { name:'Eroxxx HD',              logo:null, url:DEMO, cat:'adults', quality:'HD', country:'EU', group:'Eroxxx' },
  { name:'Spice TV',               logo:null, url:DEMO, cat:'adults', quality:'HD', country:'US', group:'Spice' },
  { name:'SexView',                logo:null, url:DEMO, cat:'adults', quality:'HD', country:'EU', group:'SexView' },

  // ════════════════════════════════════════════
  //  🌍 INTERNATIONAL COMPLÉMENTAIRES (22 chaînes)
  // ════════════════════════════════════════════

  { name:'NHK World Premium',      logo:L.NHK,  url:DEMO, cat:'international', quality:'FHD', country:'JP', group:'NHK' },
  { name:'NHK BS1',                logo:L.NHK,  url:DEMO, cat:'international', quality:'FHD', country:'JP', group:'NHK' },
  { name:'TV Tokyo',               logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'JP', group:'TV Tokyo' },
  { name:'Fuji TV',                logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'JP', group:'Fuji' },
  { name:'CCTV-4',                 logo:L.CGTN, url:DEMO, cat:'international', quality:'HD',  country:'CN', group:'CCTV' },
  { name:'Phoenix TV Chinese',     logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'HK', group:'Phoenix' },
  { name:'ATN Bengali',            logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BD', group:'ATN' },
  { name:'NTV Bangladesh',         logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BD', group:'NTV' },
  { name:'SBS World (Korea)',      logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'KR', group:'SBS' },
  { name:'MBC Korea',              logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'KR', group:'MBC KR' },
  { name:'KBS 1',                  logo:L.KBS,  url:DEMO, cat:'international', quality:'FHD', country:'KR', group:'KBS' },
  { name:'TV Cultura Brasil',      logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BR', group:'TV Cultura' },
  { name:'Bandeirantes',           logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BR', group:'Band' },
  { name:'RedeTV! Brasil',         logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'BR', group:'RedeTV' },
  { name:'Mega Greece',            logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'GR', group:'Mega GR' },
  { name:'ERT World',              logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'GR', group:'ERT' },
  { name:'TRT Türk',               logo:L.TRT,  url:DEMO, cat:'international', quality:'HD',  country:'TR', group:'TRT' },
  { name:'ATV Turkey',             logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'TR', group:'ATV' },
  { name:'SHOW TV',                logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'TR', group:'Show' },
  { name:'STAR TV Turkey',         logo:null,   url:DEMO, cat:'international', quality:'FHD', country:'TR', group:'Star TR' },
  { name:'Africa Magic',           logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'NG', group:'Africa Magic' },
  { name:'Nollywood TV',           logo:null,   url:DEMO, cat:'international', quality:'HD',  country:'NG', group:'Nollywood' },

];

module.exports = channels;
